title: Network Automation Team
lang: en
description: Architectural documentation for the Network Automation and Telemetry Workstream

remote_theme: psmware-ghpages-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
